"""empty message

Revision ID: 1e2230b27d7d
Revises: 
Create Date: 2019-07-27 12:37:47.731504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e2230b27d7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_type',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('landed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('state',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('city',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['state'], ['state.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('property',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('position', sa.Enum('Intermediate', 'Corner', 'EndLot'), nullable=True),
    sa.Column('floors', sa.Integer(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=False),
    sa.Column('plus_rooms', sa.Integer(), nullable=True),
    sa.Column('car_parks', sa.Integer(), nullable=True),
    sa.Column('studio', sa.Boolean(), nullable=False),
    sa.Column('soho', sa.Boolean(), nullable=False),
    sa.Column('penthouse', sa.Boolean(), nullable=False),
    sa.Column('sub_type', sa.Enum('Unfurnished', 'Partly Furnished', 'Fully Furnished'), nullable=True),
    sa.Column('property_type', sa.Integer(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('city', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city'], ['city.pk'], ),
    sa.ForeignKeyConstraint(['property_type'], ['property_type.pk'], ),
    sa.ForeignKeyConstraint(['state'], ['state.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property')
    op.drop_table('city')
    op.drop_table('state')
    op.drop_table('property_type')
    # ### end Alembic commands ###
