"""empty message

Revision ID: d6b45c4bd2a7
Revises: 
Create Date: 2019-08-05 21:21:49.294224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6b45c4bd2a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_type',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('landed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('state',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('city',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['state_pk'], ['state.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('town',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_pk'], ['city.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('property',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('position', sa.Enum('Intermediate', 'Corner', 'EndLot', ''), nullable=True),
    sa.Column('sub_type', sa.Enum('Duplex', 'Triplex', ''), nullable=True),
    sa.Column('floors', sa.Float(precision=1), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=False),
    sa.Column('plus_rooms', sa.Integer(), nullable=True),
    sa.Column('car_parks', sa.Integer(), nullable=True),
    sa.Column('studio', sa.Boolean(), nullable=False),
    sa.Column('soho', sa.Boolean(), nullable=False),
    sa.Column('penthouse', sa.Boolean(), nullable=False),
    sa.Column('furnishing', sa.Enum('Unfurnished', 'Partly Furnished', 'Fully Furnished'), nullable=True),
    sa.Column('property_type_pk', sa.Integer(), nullable=True),
    sa.Column('state_pk', sa.Integer(), nullable=True),
    sa.Column('city_pk', sa.Integer(), nullable=True),
    sa.Column('town_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_pk'], ['city.pk'], ),
    sa.ForeignKeyConstraint(['property_type_pk'], ['property_type.pk'], ),
    sa.ForeignKeyConstraint(['state_pk'], ['state.pk'], ),
    sa.ForeignKeyConstraint(['town_pk'], ['town.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property')
    op.drop_table('town')
    op.drop_table('city')
    op.drop_table('state')
    op.drop_table('property_type')
    # ### end Alembic commands ###
